"""empty message

Revision ID: dcd3cebe87ca
Revises: 664ac7013e71
Create Date: 2017-11-05 20:48:48.391810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd3cebe87ca'
down_revision = '664ac7013e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_file', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_file')
    # ### end Alembic commands ###
